node.default['nginx']['dir'] = "/etc/nginx"
node.default['nginx']['pid'] = "/run/nginx.pid"
node.default['nginx']['user'] = "ubuntu"
node.default['nginx']['log_dir'] = "/etc/nginx"
node.default['nginx']['source']['conf_path'] = "/etc/nginx/sites-enabled"